"""Keyword tables for domain fast-path intent detection."""

from __future__ import annotations

SQL_EXACT: dict[str, str] = {
    "select ": "select",
    "insert into": "insert",
    "update ": "update",
    "delete from": "delete",
    "delete from ": "delete",
    "create table": "create_table",
    "drop table": "drop_table",
    "alter table": "alter_table",
    "truncate ": "truncate",
    "create index": "create_index",
    "create view": "create_view",
    "create database": "create_database",
}

DOCKER_TERMS: tuple[tuple[str, str], ...] = (
    ("docker compose", "compose_up"),
    ("docker-compose", "compose_up"),
    ("compose up", "compose_up"),
    ("uruchom docker compose", "compose_up"),
    ("docker ps", "list"),
    ("docker run", "run"),
    ("docker stop", "stop"),
    ("docker start", "start"),
    ("docker rm", "remove"),
    ("docker rmi", "remove_image"),
    ("docker pull", "pull"),
    ("docker push", "push"),
    ("docker build", "build"),
    ("docker exec", "exec"),
    ("docker logs", "logs"),
    ("docker image", "images"),
    ("docker volume", "volume"),
    ("docker network", "network"),
    ("docker ", "list"),
)

DOCKER_CONTAINER_ACTIONS: tuple[tuple[str, str], ...] = (
    ("uruchom kontener", "run"),
    ("run container", "run"),
    ("start container", "start"),
    ("uruchom container", "run"),
    ("run kontener", "run"),
    ("start kontener", "start"),
    ("zatrzymaj kontener", "stop"),
    ("stop container", "stop"),
    ("zatrzymaj container", "stop"),
    ("stop kontener", "stop"),
    ("uruchom zatrzymany kontener", "start"),
    ("usuń kontener", "remove"),
    ("remove container", "remove"),
    ("delete container", "remove"),
    ("usun kontener", "remove"),
    ("remove kontener", "remove"),
    ("delete kontener", "remove"),
    ("wykonaj komendę w kontenerze", "exec"),
    ("wykonaj polecenie w kontenerze", "exec"),
    ("exec in container", "exec"),
    ("wejdź do kontenera", "exec"),
    ("shell kontenera", "exec"),
    ("wejdź do container", "exec"),
    ("shell container", "exec"),
    ("pokaż logi kontenera", "logs"),
    ("container logs", "logs"),
    ("pokaż logi container", "logs"),
    ("logi kontenera", "logs"),
    ("pobierz obraz", "pull"),
    ("pull image", "pull"),
    ("ściągnij obraz", "pull"),
    ("pobierz image", "pull"),
    ("sciagnij image", "pull"),
    ("pull obraz", "pull"),
    ("wypchnij obraz", "push"),
    ("wyślij obraz", "push"),
    ("push image", "push"),
    ("wypchnij image", "push"),
    ("push obraz", "push"),
    ("opublikuj obraz", "push"),
    ("wypchnij", "push"),
    ("zbuduj obraz", "build"),
    ("build image", "build"),
    ("zbuduj image", "build"),
    ("build obraz", "build"),
    ("stwórz obraz", "build"),
    ("list containers", "list"),
    ("pokaż kontenery", "list"),
    ("kontenery docker", "list"),
    ("docker containers", "list"),
    ("kontener", "list"),
    ("container", "list"),
)

K8S_TERMS: tuple[tuple[str, str], ...] = (
    ("kubectl ", "get"),
    ("kubernetes", "get"),
    ("k8s", "get"),
    ("opisz deployment", "describe"),
    ("opisz pod", "describe"),
    ("describe deployment", "describe"),
    ("describe pod", "describe"),
    ("skaluj deployment", "scale"),
    ("scale deployment", "scale"),
    ("skaluj do", "scale"),
    ("scale to", "scale"),
    ("stwórz serwis", "create_service"),
    ("create service", "create_service"),
    ("utwórz serwis", "create_service"),
    ("stwórz configmap", "create_configmap"),
    ("create configmap", "create_configmap"),
    ("utwórz configmap", "create_configmap"),
    ("stwórz secret", "create_secret"),
    ("create secret", "create_secret"),
    ("utwórz secret", "create_secret"),
    ("stwórz ingress", "create_ingress"),
    ("create ingress", "create_ingress"),
    ("utwórz ingress", "create_ingress"),
    ("stwórz deployment", "create"),
    ("create deployment", "create"),
    ("utwórz deployment", "create"),
    ("stwórz zasób", "create"),
    ("utwórz namespace", "create"),
    ("create namespace", "create"),
    ("pokaż logi poda", "logs"),
    ("pod logs", "logs"),
    ("pody w klastrze", "get"),
    ("pods in cluster", "get"),
    ("pokaż pody", "get"),
    ("show pods", "get"),
    ("get pods", "get"),
    (" pods", "get"),
    ("pod ", "get"),
    (" pod ", "get"),
    ("deployment", "get"),
    ("namespace", "get"),
    ("klaster", "get"),
    ("cluster", "get"),
    ("ingress", "get"),
    ("configmap", "get"),
    ("secret", "get"),
    ("service mesh", "get"),
    ("helm ", "get"),
)

SHELL_TERMS: dict[str, str] = {
    "configuration files": "find",
    "config files": "find",
    "find files": "find",
    "find file": "find",
    "search files": "find",
    "search for files": "find",
    "pliki konfiguracyjne": "find",
    "znajdź pliki": "find",
    "znajdź plik": "find",
    "zawartość katalogu": "list",
    "zawartość folderu": "list",
    "directory contents": "list",
    "folder contents": "list",
    "list files": "list",
    "list directory": "list",
    "pokaż pliki": "list",
    "pokaz pliki": "list",
    "lista plików": "list",
    "lista plikow": "list",
    "show files": "list",
    "show file": "list",
    "uruchomione procesy": "list_processes",
    "running processes": "list_processes",
    "pokaż procesy": "list_processes",
    "show processes": "list_processes",
    "miejsce na dysku": "disk_usage",
    "disk space": "disk_usage",
    "disk usage": "disk_usage",
    "wolne miejsce": "disk_usage",
    "sprawdź dysk": "disk_usage",
    "grep ": "search",
    "szukaj w pliku": "search",
    "search in file": "search",
    "znajdź słowo": "search",
    "szukaj w logach": "search",
    "skopiuj plik": "copy",
    "copy file": "copy",
    "skopiuj ": "copy",
    "przenieś plik": "move",
    "move file": "move",
    "przenieś ": "move",
    "usuń plik": "remove",
    "delete file": "remove",
    "usuń stary": "remove",
    "usun plik": "remove",
    "skasuj plik": "remove",
    "skasuj": "remove",
    "zmień uprawnienia": "permissions_chmod",
    "uprawnienia pliku": "permissions_chmod",
    "change permissions": "permissions_chmod",
    "chmod ": "permissions_chmod",
    "spakuj folder": "compress_tar",
    "spakuj ": "compress_tar",
    "compress folder": "compress_tar",
    "skompresuj": "compress_tar",
    "utwórz katalog": "create_dir",
    "utwórz folder": "create_dir",
    "stwórz katalog": "create_dir",
    "stwórz folder": "create_dir",
    "create directory": "create_dir",
    "make directory": "create_dir",
    "mkdir ": "create_dir",
    "zabij proces": "process_kill",
    "zakończ proces": "process_kill",
    "kill process": "process_kill",
    "terminate process": "process_kill",
    "kill ": "process_kill",
    "interfejsy sieciowe": "network_interfaces",
    "network interfaces": "network_interfaces",
    "show network": "network_interfaces",
    "adresy ip": "network_interfaces",
    "ip addr": "network_interfaces",
    "ifconfig": "network_interfaces",
}

BROWSER_CONTEXT_SIGNALS: frozenset[str] = frozenset(
    {"klucz", "key", "api", "token", ".env", "stron", "przegladark", "przeglądark"}
)

SQL_NL: tuple[tuple[str, str], ...] = (
    ("stwórz tabelę", "create_table"),
    ("utwórz tabelę", "create_table"),
    ("create table", "create_table"),
    ("nowa tabela", "create_table"),
    ("usuń tabelę", "drop_table"),
    ("skasuj tabelę", "drop_table"),
    ("drop table", "drop_table"),
    ("zniszcz tabelę", "drop_table"),
    ("dodaj nowy rekord", "insert"),
    ("dodaj rekord", "insert"),
    ("add new record", "insert"),
    ("add record", "insert"),
    ("wstaw rekord", "insert"),
    ("insert record", "insert"),
    ("zaktualizuj status", "update"),
    ("zaktualizuj rekord", "update"),
    ("update record", "update"),
    ("zmień wartość", "update"),
    ("usuń rekord", "delete"),
    ("delete record", "delete"),
    ("skasuj rekord", "delete"),
    ("usuń stare dane", "delete"),
    ("usuń dane", "delete"),
    ("delete old data", "delete"),
    ("remove old data", "delete"),
    ("policz liczbę", "aggregate"),
    ("policz rekordy", "aggregate"),
    ("count(", "aggregate"),
    ("sum(", "aggregate"),
    ("avg(", "aggregate"),
    ("zsumuj", "aggregate"),
    ("count records", "aggregate"),
    ("inner join", "join"),
    ("left join", "join"),
    ("right join", "join"),
    ("join tables", "join"),
    ("połącz tabele", "join"),
    ("złącz tabele", "join"),
    ("from the table", "select"),
    ("from table", "select"),
    ("z tabeli", "select"),
    ("wyświetl dane", "select"),
    ("pokaż rekordy", "select"),
    ("show records", "select"),
    ("all users", "select"),
    ("all records", "select"),
    ("wszystkich użytkowników", "select"),
    ("wszystkie rekordy", "select"),
    ("pokaż użytkowników", "select"),
    ("show users", "select"),
    ("lista użytkowników", "select"),
    ("list users", "select"),
    ("pokaż dane", "select"),
    ("show data", "select"),
    ("wyświetl dane", "select"),
    ("display data", "select"),
    (" tabeli ", "select"),
    (" table ", "select"),
    ("rekordów", "select"),
    ("rekordow", "select"),
    ("records", "select"),
    ("wierszy", "select"),
    ("rows", "select"),
)

BROWSER_PHRASE_PATTERNS: tuple[tuple[str, str, str], ...] = (
    (r"otw[oó]rz\s+przegl[aą]dark[eę]", "browser", "open_browser"),
    (r"uruchom\s+przegl[aą]dark[eę]", "browser", "open_browser"),
    (r"w[łl][aą]cz\s+przegl[aą]dark[eę]", "browser", "open_browser"),
    (r"(?:wejd[zź]|przejd[zź]|id[zź])\s+na\s+stron[eę]", "browser", "navigate"),
    (r"otw[oó]rz\s+stron[eę]", "browser", "navigate"),
    (r"(?:otw[oó]rz|wejd[zź]|uruchom).+\.[a-z]{2,}", "browser", "navigate"),
    (r"(?:nowy|otw[oó]rz)\s+tab", "browser", "new_tab"),
    (r"now[aą]\s+kart[eę]", "browser", "new_tab"),
    (r"(?:otw[oó]rz|open)\s+\d+\s+(?:tab|kart)", "browser", "new_tab"),
    (r"(?:wyci[aą]gnij|skopiuj|pobierz).+(?:klucz|key|token|api)", "browser", "extract_data"),
    (r"zapiszs*\s+(?:do|w)\s+\.env", "browser", "save_env"),
    (r"zapi[sś]z?\s+(?:do|w)\s+\.env", "browser", "save_env"),
    (r"(?:wype[lł]nij|uzupe[lł]nij)\s+formul", "browser", "fill_form"),
)

BROWSER_COMPLEX: tuple[tuple[str, str, str], ...] = (
    ("znajdź formularz i wypełnij", "browser", "explore_and_fill"),
    ("znajdz formularz i wypelnij", "browser", "explore_and_fill"),
    ("znajdź stronę kontaktu i wypełnij", "browser", "explore_and_fill"),
    ("znajdz strone kontaktu i wypelnij", "browser", "explore_and_fill"),
    ("find form and fill", "browser", "explore_and_fill"),
    ("szukaj kontaktu i wypełnij", "browser", "explore_and_fill"),
    ("szukaj kontaktu i wypelnij", "browser", "explore_and_fill"),
    ("znajdź formularz", "browser", "find_form"),
    ("znajdz formularz", "browser", "find_form"),
    ("szukaj formularza", "browser", "find_form"),
    ("find form", "browser", "find_form"),
    ("search form", "browser", "find_form"),
    ("locate form", "browser", "find_form"),
    ("znajdź stronę kontaktu", "browser", "find_form"),
    ("znajdz strone kontaktu", "browser", "find_form"),
    ("szukaj kontaktu", "browser", "find_form"),
    ("znajdź kontakt", "browser", "find_form"),
)

USER_TABLE_KEYWORDS: frozenset[str] = frozenset(
    {"pokaż użytkowników", "show users", "lista użytkowników", "list users"}
)

LIMIT_KEYWORDS: frozenset[str] = frozenset(
    {"rekordów", "rekordow", "records", "wierszy", "rows"}
)

TABLE_NAME_KEYWORDS: frozenset[str] = frozenset(
    {"z tabeli", "from table", "from the table"}
)
